[package]
name = "utils-wasm"
version = "0.3.3"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.88"
serde = { version = "1.0.192", features = ["derive"] }
serde-wasm-bindgen = "0.6.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
tsify = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
console-error-panic = ["console_error_panic_hook"]