name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1

            - name: Update Submodules
              run: git submodule update --init --recursive

            - run: curl -L https://install.dojoengine.org | bash
            - run: /home/runner/.config/.dojo/bin/dojoup -v v0.5.0
            - run: |
                  cd examples/dojo-starter
                  /home/runner/.config/.dojo/bin/sozo build
                  /home/runner/.config/.dojo/bin/sozo test

            - name: Install Protobuf Compiler
              run: sudo apt-get install -y protobuf-compiler

            - name: Link dependencies
              run: bun link

            - name: Install dependencies
              run: bun install

            - name: Run Prettier
              run: bun x prettier --check .

            - name: Build dependencies
              run: bun run build && bun run build-examples

            # - name: Upload coverage reports to Codecov
            #   uses: codecov/codecov-action@v3
            #   env:
            #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
